{% set data = load_setup_py_data(setup_file='python/setup.py') %}

package:
  name: lattice-symmetries
  version: {{ data.get('version') }}

source:
  # git_url: https://github.com/twesterhout/nqs-playground
  # git_rev: develop
  path: ../

build:
  number: 0
 
requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]

  host:
    - python
    - pip
    - numpy
    - scipy

  run:
    - python
    - libstdcxx-ng # [linux]
    - libgcc-ng # [linux]
    # - libcxxabi # [osx]
    - numpy
    - scipy
    - h5py
    - pyyaml
