{% set data = load_setup_py_data(setup_file='python/setup.py') %}

package:
  name: lattice-symmetries
  version: {{ data.get('version') }}

source:
  # git_url: https://github.com/twesterhout/nqs-playground
  # git_rev: develop
  path: ../

build:
  number: 3
 
requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - numpy
    - scipy

  run:
    - python
    - libstdcxx-ng
    - libgcc-ng
    - numpy
    - scipy
