name: Conda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug
  INSTALL_LOCATION: .local

jobs:
  # build:
  #   name: Build within Conda on ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest]

  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       submodules: true
  #   - uses: conda-incubator/setup-miniconda@v2
  #     if: matrix.os == 'ubuntu-latest'
  #     with:
  #       activate-environment: lattice_symmetries_devel
  #       environment-file: conda-devel-linux.yml
  #       auto-activate-base: false
  #   - uses: conda-incubator/setup-miniconda@v2
  #     if: matrix.os == 'macos-latest'
  #     with:
  #       activate-environment: lattice_symmetries_devel
  #       environment-file: conda-devel-osx.yml
  #       auto-activate-base: false
  #   
  #   - name: Info
  #     run: |
  #       conda info
  #       conda env list

  #   - name: Build 
  #     run: |
  #       if [[ -d /usr/local/miniconda/etc ]]; then
  #         source /usr/local/miniconda/etc/profile.d/conda.sh
  #       else
  #         source /usr/share/miniconda/etc/profile.d/conda.sh
  #       fi
  #       conda activate lattice_symmetries_devel
  #       cmake -GNinja \
  #             -Bbuild \
  #             -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
  #             -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION
  #       cmake --build build
  #     
  #   - name: Run tests
  #     run: |
  #       cd build
  #       ctest -VV

  #   - name: Install
  #     run: cmake --build build --target install

  conda_package:
    name: Build Conda package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
    
    - name: Info
      run: |
        conda info
        conda env list
        conda install anaconda-client conda-build conda-verify

    - name: Build 
      run: |
        if [[ $(uname) != "Linux" ]]; then
          wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz
          sudo tar xf MacOSX11.3.sdk.tar.xz -C /opt
          echo "" >> conda/conda_build_config.yaml
          echo "CONDA_BUILD_SYSROOT:" >> conda/conda_build_config.yaml
          echo "  - /opt/MacOSX11.3.sdk        # [osx]" >> conda/conda_build_config.yaml
        fi
        mkdir conda_output
        conda build -c conda-forge conda --output-folder=$PWD/conda_output
