name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug
  INSTALL_LOCATION: .local

jobs:
  build:
    strategy:
      matrix:
        gcc-version: [7, 8, 9, 10]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
      
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install g++-${{ matrix.gcc-version }} gcc-${{ matrix.gcc-version }}

    - name: configure
      run: |
        cmake -Bbuild \
              -DCMAKE_CXX_COMPILER=g++-${{ matrix.gcc-version }} \
              -DCMAKE_C_COMPILER=gcc-${{ matrix.gcc-version }} \
              -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
              -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION
      
    - name: build
      run: cmake --build build -j4

    - name: run tests
      run: |
        cd build
        ctest -VV

    - name: install project
      run: cmake --build build --target install
